parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    mailer_transport="gmail"
    mailer_encryption="ssl"
    mailer_auth_mode="login"
    mailer_host="smtp.gmail.com"
    mailer_user="xxxxx"
    mailer_password="aaaaa"
    locale: en
    secret: 6812dbce46c3c0c4fbe6422bcafa72b3979880f7
    database_path: null
